plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':quiz-api')
    implementation project(':quiz-infrastructure')

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    testImplementation project(':quiz-domain')
    testImplementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    testRuntimeOnly 'com.h2database:h2'
}

bootJar {
    archiveFileName = 'teamsky.jar'
}

jar {
    enabled = false
}
